# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 630)
        MainWindow.setMinimumSize(QtCore.QSize(775, 630))
        MainWindow.setMaximumSize(QtCore.QSize(775, 630))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-13, -60, 850, 690))
        self.widget.setMinimumSize(QtCore.QSize(850, 690))
        self.widget.setMaximumSize(QtCore.QSize(850, 690))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.278, x2:0.573, y2:0.784091, stop:0 rgba(1, 38, 78, 255), stop:1 rgba(171, 119, 143, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(349, 184, 111, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("background-color:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("src/ss (2).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(139, 257, 541, 361))
        self.label_2.setStyleSheet("background-color:#c5bacc;\n"
" border-radius: 10px ;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(274, 374, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setStyleSheet("background-color:none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("src/login.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(278, 416, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setStyleSheet("background-color:none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("src/phone-call.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(312, 494, 211, 31))
        self.lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:#496874;\n"
"border:none;\n"
"border-radius:10px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(312, 380, 211, 31))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:#496874;\n"
"border:none;\n"
"border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(569, 579, 81, 20))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setStyleSheet("background-color:#093545;\n"
"border-radius:10px;\n"
"color:white;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(312, 417, 211, 31))
        self.lineEdit_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:#496874;\n"
"border:none;\n"
"border-radius:10px;")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(312, 455, 211, 31))
        self.lineEdit_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:#496874;\n"
"border:none;\n"
"border-radius:10px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(347, 327, 131, 41))
        self.lineEdit_6.setStyleSheet("font: 24pt \"Tahoma\";\n"
"border-radius:15px;\n"
"color:#093545;\n"
"background-color:#c5bacc;\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(278, 494, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("background-color:none;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("src/padlock.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(278, 455, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setStyleSheet("background-color:none;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("src/email.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.btnSignup = QtWidgets.QPushButton(self.widget)
        self.btnSignup.setGeometry(QtCore.QRect(369, 538, 81, 21))
        self.btnSignup.setMouseTracking(False)
        self.btnSignup.setStyleSheet("#btnSignup\n"
"{\n"
"background-color:#093545;\n"
"border-radius:10px;\n"
"color:white;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;\n"
"}\n"
"#btnSignup:hover{\n"
"background-color:green;\n"
"}\n"
"")
        self.btnSignup.setCheckable(False)
        self.btnSignup.setObjectName("btnSignup")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(429, 580, 131, 20))
        self.label_7.setStyleSheet("background-color:#c5bacc;")
        self.label_7.setObjectName("label_7")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.btnSignup.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "  Password"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "  Full Name"))
        self.pushButton_2.setText(_translate("MainWindow", "LOGIN"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", " Phone Number"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", " User Email"))
        self.lineEdit_6.setText(_translate("MainWindow", "SIGNUP"))
        self.btnSignup.setText(_translate("MainWindow", "SIGNUP"))
        self.label_7.setText(_translate("MainWindow", "Already have an account??"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())