# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminnotification.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 690)
        MainWindow.setMinimumSize(QtCore.QSize(850, 690))
        MainWindow.setMaximumSize(QtCore.QSize(850, 690))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QWidget(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -20, 851, 771))
        self.background.setStyleSheet("background-color:#f8f8f8;")
        self.background.setObjectName("background")
        self.notifbox = QtWidgets.QLabel(self.background)
        self.notifbox.setGeometry(QtCore.QRect(-1, 16, 171, 701))
        self.notifbox.setStyleSheet("background-color:#01264e;\n"
" border-radius: 10px ;")
        self.notifbox.setText("")
        self.notifbox.setObjectName("notifbox")
        self.notifpushButton = QtWidgets.QPushButton(self.background)
        self.notifpushButton.setGeometry(QtCore.QRect(0, 220, 171, 41))
        self.notifpushButton.setMouseTracking(False)
        self.notifpushButton.setStyleSheet("background-color:white;\n"
" border: 2px solid;\n"
"border-color: #c88486;\n"
"color:black;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;")
        self.notifpushButton.setCheckable(False)
        self.notifpushButton.setObjectName("notifpushButton")
        self.opporbox = QtWidgets.QLabel(self.background)
        self.opporbox.setGeometry(QtCore.QRect(170, 220, 721, 511))
        self.opporbox.setStyleSheet("\n"
" border-radius: 1px ;")
        self.opporbox.setText("")
        self.opporbox.setObjectName("opporbox")
        self.eventbox = QtWidgets.QLabel(self.background)
        self.eventbox.setGeometry(QtCore.QRect(170, 20, 681, 201))
        self.eventbox.setStyleSheet("\n"
"background-color:#c88486;\n"
" border-radius: 1px ;")
        self.eventbox.setText("")
        self.eventbox.setObjectName("eventbox")
        self.opporpushButton = QtWidgets.QPushButton(self.background)
        self.opporpushButton.setGeometry(QtCore.QRect(0, 270, 171, 41))
        self.opporpushButton.setMouseTracking(False)
        self.opporpushButton.setStyleSheet("background-color:white;\n"
" border: 2px solid;\n"
"border-color: #c88486;\n"
"color:black;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;")
        self.opporpushButton.setCheckable(False)
        self.opporpushButton.setObjectName("opporpushButton")
        self.eventpushButton = QtWidgets.QPushButton(self.background)
        self.eventpushButton.setGeometry(QtCore.QRect(0, 370, 171, 41))
        self.eventpushButton.setMouseTracking(False)
        self.eventpushButton.setStyleSheet("background-color:white;\n"
" border: 2px solid;\n"
"border-color: #c88486;\n"
"color:black;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;")
        self.eventpushButton.setCheckable(False)
        self.eventpushButton.setObjectName("eventpushButton")
        self.perslpushButton = QtWidgets.QPushButton(self.background)
        self.perslpushButton.setGeometry(QtCore.QRect(0, 320, 171, 41))
        self.perslpushButton.setMouseTracking(False)
        self.perslpushButton.setStyleSheet("background-color:white;\n"
" border: 2px solid;\n"
"border-color: #c88486;\n"
"color:black;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;")
        self.perslpushButton.setCheckable(False)
        self.perslpushButton.setObjectName("perslpushButton")
        self.maintext = QtWidgets.QLabel(self.background)
        self.maintext.setGeometry(QtCore.QRect(235, 170, 541, 51))
        self.maintext.setStyleSheet("font: 24pt \"Tahoma\";\n"
"border-radius:10px;\n"
"color:white;\n"
"background-color: #01264e;")
        self.maintext.setObjectName("maintext")
        self.pushButton_5 = QtWidgets.QPushButton(self.background)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 480, 171, 41))
        self.pushButton_5.setStyleSheet("background-color:#01264e;\n"
"border-radius:10px;\n"
"color:white;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.uetlogo = QtWidgets.QLabel(self.background)
        self.uetlogo.setGeometry(QtCore.QRect(200, 40, 81, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.uetlogo.sizePolicy().hasHeightForWidth())
        self.uetlogo.setSizePolicy(sizePolicy)
        self.uetlogo.setMinimumSize(QtCore.QSize(0, 0))
        self.uetlogo.setStyleSheet("background-color:none;")
        self.uetlogo.setText("")
        self.uetlogo.setPixmap(QtGui.QPixmap("src/uetlogo.png"))
        self.uetlogo.setScaledContents(True)
        self.uetlogo.setObjectName("uetlogo")
        self.perslimg = QtWidgets.QLabel(self.background)
        self.perslimg.setGeometry(QtCore.QRect(20, 30, 121, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.perslimg.sizePolicy().hasHeightForWidth())
        self.perslimg.setSizePolicy(sizePolicy)
        self.perslimg.setMinimumSize(QtCore.QSize(0, 0))
        self.perslimg.setStyleSheet("background-color:none;\n"
"")
        self.perslimg.setText("")
        self.perslimg.setPixmap(QtGui.QPixmap("src/setting (1).png"))
        self.perslimg.setScaledContents(True)
        self.perslimg.setObjectName("perslimg")
        self.cslogo_2 = QtWidgets.QLabel(self.background)
        self.cslogo_2.setGeometry(QtCore.QRect(730, 40, 81, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(63)
        sizePolicy.setHeightForWidth(self.cslogo_2.sizePolicy().hasHeightForWidth())
        self.cslogo_2.setSizePolicy(sizePolicy)
        self.cslogo_2.setMinimumSize(QtCore.QSize(0, 0))
        self.cslogo_2.setStyleSheet("background-color:none;")
        self.cslogo_2.setText("")
        self.cslogo_2.setPixmap(QtGui.QPixmap("src/cs.png"))
        self.cslogo_2.setScaledContents(True)
        self.cslogo_2.setObjectName("cslogo_2")
        self.tableWidget = QtWidgets.QTableWidget(self.background)
        self.tableWidget.setGeometry(QtCore.QRect(270, 270, 391, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.background)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 480, 171, 41))
        self.pushButton_6.setStyleSheet("background-color:#01264e;\n"
"border-radius:10px;\n"
"color:white;\n"
"font: 75 10pt \"Tahoma\";\n"
"letter-spacing: 2 px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.notifbox.raise_()
        self.opporbox.raise_()
        self.eventbox.raise_()
        self.opporpushButton.raise_()
        self.eventpushButton.raise_()
        self.perslpushButton.raise_()
        self.maintext.raise_()
        self.pushButton_5.raise_()
        self.uetlogo.raise_()
        self.perslimg.raise_()
        self.notifpushButton.raise_()
        self.cslogo_2.raise_()
        self.tableWidget.raise_()
        self.pushButton_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.notifpushButton.setText(_translate("MainWindow", "NOTIFICATION"))
        self.opporpushButton.setText(_translate("MainWindow", "OPPORTUNITIES"))
        self.eventpushButton.setText(_translate("MainWindow", "EVENTS"))
        self.perslpushButton.setText(_translate("MainWindow", "Personal Information"))
        self.maintext.setText(_translate("MainWindow", "    SMART NOTIFICATION BOARD"))
        self.pushButton_5.setText(_translate("MainWindow", "GENER"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.pushButton_6.setText(_translate("MainWindow", "GENER"))
